### ISSUE TITLE
Send 0.11 to Rubygems

### ISSUE THREAD

**Issue by Ruxton** [carrierwaveuploader/carrierwave#1894]
0.11 isn't on rubygems, there's fixes in it for things like RMagick deprecations. Can someone make it goto rubygems so people using that source actually get the updated version?

It's also not tagged in the releases section on github for some reason?

**Comment by CUnknown** [comment]
@kreintjes already made a pull request to update everything for a new release (changelog ed). https://github.com/carrierwaveuploader/carrierwave/pull/1883 It only needs to be merged and submitted to rubygems, but this can only be performed by the owners of the repo, I think.

**Comment by pnicolai** [comment]
:+1:

**Comment by kernow** [comment]
Is anyone able to explain whats going on with releasing this gem to rubygems? The current version on rubygems is 2 years old, the documentation isn't clear on how to install and from what source depending on your rails version. I'm wondering if I should be moving to another solution if the maintainers are going to ditch the standard way to distributing a gem.

**Comment by CUnknown** [comment]
Time to create a new 'carrierwavewave' gem?

**Comment by AlexLarra** [comment]
:+1:

**Comment by thedrow** [comment]
Hi guys please release or add more maintainers and grant them release rights.
I can volunteer to craft this release if needed.

**Comment by thiagofm** [comment]
Hello everyone. Sorry for the delay.

Sadly, even though I'm a "owner", I don't have the permissions to generate the release. I've sent an e-mail for the maintainers that are able to generate a release in Rubygems in order to fix this problem.

Thanks a lot for your feedback, I'll leave this open until we generate a release.

**Comment by thedrow** [comment]
@thiagofm In order to prevent this problem in the future let's setup Travis to deploy to rubygems whenever the repository is tagged.
That way, any contributor with commit access can release when it's needed.

**Comment by thiagofm** [comment]
@thedrow feel free to submit a PR, I was just reading about that.

**Comment by thedrow** [comment]
In order to submit a PR I'll need your credentials and access to Travis in order to encrypt them.
You can do it yourself using the travis command line tool.

**Comment by thiagofm** [comment]
@thedrow okay, thanks.

**Comment by thiagofm** [comment]
I've done the release, have fun people!

**Comment by kreintjes** [comment]
@thiagofm thanks for the release, but shouldn't you have merged my changelog updates first? :p
https://github.com/carrierwaveuploader/carrierwave/pull/1883

**Comment by thiagofm** [comment]
Sorry @kreintjes. I wasn't aware of that. I've merged it now. Do you thing there's a need to regenerate the release? :P

**Comment by kreintjes** [comment]
No problem @thiagofm. It is just changelog updates, so I don't think it is really necessary. Most people will probably look on Github for the readme and changelog anyway.

However, after upgrading to 0.11.0 I noticed some deprecation warnings I got are not fixed yet. I backported the corresponding fixes to the 0.11-stable branch: https://github.com/carrierwaveuploader/carrierwave/pull/1908. Perhaps you could merge this and do another release? (A) I guess this would be 0.11.1 then, since it is only a fix and should be backwards compatible.

**Comment by thiagofm** [comment]
@kreintjes thanks for taking your time to test the new release. I'll do this ASAP.
